### ISSUE TITLE
Variable Schriftgrößen führen bei sehr breiten Auflösungen zu Fehlern im Layout 

### ISSUE THREAD

**Issue by SandroGlueck** [DetektivKollektiv/angular-ui#139]
Auf 32:9 Monitoren (z.B. 3440 x 1440 px) führt die variable Schriftgröße von `<p>` zu Problemen bei einigen Layout Elementen (z.B. Planten auf Über Uns Seite).

[styles.scss](https://github.com/DetektivKollektiv/angular-ui/blob/56953d50d10f02a128d6feec9ed4e98f61b4c7de/src/styles.scss#L125)
```css
p {
  @include font__effra--regular;
  font-size: max(0.7vw, 14px);
  line-height: max(1vw, 22px);
}
```

![image](https://user-images.githubusercontent.com/38329766/148113593-ea5eb42e-2709-44bd-8aa8-672d11dea1e8.png)
